# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Manuel Jesús Brenes Flores
# Website URL
baseURL: 'http://mjbf.eu/'

############################
## LANGUAGE
############################

defaultContentLanguage: es
hasCJKLanguage: false
defaultContentLanguageInSubdir: true
removePathAccents: true

languages:
  es:
    weight: 1
    title: "Manuel Jesús Brenes Flores"
    languageName: "Español"
  en:
    weight: 2
    title: "Manuel Jesús Brenes Flores"
    languageName: "English"
  fr:
    weight: 3
    title: "Manuel Jesús Brenes Flores"
    languageName: "Français"
  it:
    weight: 4
    title: "Manuel Jesús Brenes Flores"
    languageName: "Italiano"
  de:
    weight: 5
    title: "Manuel Jesús Brenes Flores"
    languageName: "Deutsch"

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/authors/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
