en:
  languageCode: en-us
  contentDir: content
  title: "Manuel Jesús Brenes Flores"
  params:
    description: "Website in English"
    favicon: "/favicon.ico"
  menu:
    main:
      - name: Bio
        url: /
        weight: 10
      - name: Publications
        url: "https://orcid.org/0009-0007-3934-8994"
        weight: 20
      - name: Preprints
        url: ""
        weight: 30
      - name: Lexora
        url: "https://manueljbren.substack.com"
        weight: 40
      - name: CV
        url: "uploads/CV-MANUEL-BRENES.pdf"
        weight: 50
      - name: Profesional
        url: /profesional/
        weight: 60

