main:
  - name: Bio
    url: /
    weight: 10
  - name: Publications
    url: "https://orcid.org/0009-0007-3934-8994"
    weight: 11
  - name: Preprints
    url: "https://zenodo.org/records/XXXXXXX"
    weight: 12
  - name: Lexora
    url: "https://manueljbren.substack.com"
    weight: 13
  - name: Despacho
    url: "https://www.brenesabogado.es"
    weight: 20
  - name: Resume
    url: Resume/
    weight: 40
