main:
  - name: Bio
    url: /
    weight: 10
  - name: Publicaciones
    url: "https://orcid.org/0009-0007-3934-8994"
    weight: 20
  - name: Preprints
    url: "https://zenodo.org/records/XXXXXXX"
    weight: 30
  - name: Lexora
    url: "https://manueljbren.substack.com"
    weight: 40
  - name: CV
    url: "uploads/resume.pdf"
    weight: 50
