# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'LAWYER AND RESEARCHER IN PRIVATE INTERNATIONAL LAW. INTERNATIONAL INHERITANCE.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Manuel Jesús Brenes Flores"

# Favicon
favicon: "favicon.ico"

# Site footer
footer:
  show_powered_by: false
  copyright:
    notice: '© {year} Manuel J. Brenes Flores. All rights reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  custom_css: ["css/custom.css"]

  customJS:
    - js/custom.js

